spring.application.name=petlink-backend

#spring.datasource.url=jdbc:postgresql://localhost:5432/petlinkdb
spring.datasource.url=jdbc:postgresql://dpg-d4b89m7diees73adjdjg-a.oregon-postgres.render.com:5432/petlink_database
#spring.datasource.username=postgres
#spring.datasource.password=postgres
# Credenciales de la base de datos
spring.datasource.username=petlink_database_user
spring.datasource.password=KDLLVSpdjTE36JQhn5jkeuqNGPVKsNP0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuraciones adicionales para conexión SSL (Render requiere SSL)
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.port=8080
spring.application.name=petlink-backend
